### ISSUE TITLE
Support for TV Series?

### ISSUE THREAD

**Issue by murdercode** [Astrotomic/laravel-tmdb#1]
Hi,
is an update for TV series support expected soon?
I'm working on a fork of mine but I don't want that in a few days the "official support" comes out and I'm forced to throw everything :)
Of course, if it helps, I'll turn you a pull-request.
Regards,

**Comment by Gummibeer** [comment]
Hey,
at all: yes, TV-Show support is wanted. But as Series, Episodes and Person relations are much more complex for them I haven't touched it yet as I want to do it right or nothing.^^

Besides that there's absolutely no ETA as I've stopped doing open-source actively. So I don't know when I would/could review/accept/merge/release a PR nor when I will write it my own. It could be next week or next year or next decade or never.^^
https://gummibeer.dev/blog/2022/end-of-an-era/
